DELETE http://localhost:3001/api/blogs/641a16d02ef35fd2221db336
Content-Type: application/json 
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjExMjI0IiwiaWQiOiI2NDIwYTZkMDVkYTEzZDNlMGMxNTg2YjkiLCJpYXQiOjE2Nzk4NjUxNzl9.lQi3sec4WYMgQ1hWlWZaX8Vd2AFf_zv4_Su_RiS6baY
