GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/641a1acb91e3d68c19af163f

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "1 23523523523523523post",
    "author": "se23523523525vd52352523525235235e",
    "url": "https://example.com/blogposts/blogid",
    "likes": 1
}

###
DELETE http://localhost:3001/api/blogs/641a1acb91e3d68c19af163f

###

PUT http://localhost:3001/api/blogs/641a16d02ef35fd2221db336
Content-Type: application/json

{
    "title": "123",
    "author": "124",
    "url": "https://example.com/blogposts/blogid",
    "likes": 235234234
}
