GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "thşrd post",
    "author": "3",
    "url": "https://example.com/blogposts/blogid"
}
